name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      spec:
        description: "Digger spec file"
        required: true
      run_name:
        description: "Optional run name"
        required: false

run-name: '${{ inputs.run_name }}'

jobs:
  digger-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Required to merge PRs
      id-token: write      # Required for OIDC authentication
      pull-requests: write # Required to post PR comments
      issues: read         # Required to check if PR number is an issue or not
      statuses: write      # Required to validate combined PR status

    steps:
      - uses: actions/checkout@v4

      - name: Parse Account ID from accounts.hcl
        id: parse-account
        run: |
          ACCOUNT_ID=$(grep -oP '(?<=account_id = )\d+' accounts/${{ github.event.inputs.spec }}/account.hcl)
          echo "account_id=${ACCOUNT_ID}" >> $GITHUB_ENV
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Digger Run
        uses: diggerhq/digger@vLatest
        with:
          digger-spec: ${{ inputs.spec }}
          setup-aws: true
          aws-role-to-assume: arn:aws:iam::${{ env.account_id }}:role/digger
          aws-region: us-east-1
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
