name: Terragrunt CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger for apply

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.filter.outputs.dirs }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Changed Directories
        id: filter
        run: |
          # Find all modified directories containing terragrunt.hcl files inside accounts directory
          CHANGED_DIRS=$(git diff --name-only origin/main...HEAD | grep 'terragrunt-live/accounts/.*terragrunt.hcl' | xargs -n1 dirname | sort -u | jq -R -s -c 'split("\n")[:-1]')
          if [[ -z "$CHANGED_DIRS" ]]; then
            CHANGED_DIRS='[]' # Default to empty JSON array
          fi
          echo "dirs=$CHANGED_DIRS" >> $GITHUB_ENV
          echo "dirs=$CHANGED_DIRS" > $GITHUB_OUTPUT

  validate-plan:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.dirs != '[]' }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.detect-changes.outputs.dirs) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Install Terragrunt
        run: |
          sudo curl -L -o /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.0/terragrunt_linux_amd64
          sudo chmod +x /usr/local/bin/terragrunt

      - name: Terragrunt Format
        run: |
          terragrunt hclfmt --terragrunt-working-dir=${{ matrix.dir }}

      - name: Terragrunt Validate
        run: |
          terragrunt validate-all --terragrunt-working-dir=${{ matrix.dir }}

      - name: Terragrunt Plan
        run: |
          terragrunt run-all plan --terragrunt-working-dir=${{ matrix.dir }} --terragrunt-non-interactive

  apply:
    runs-on: ubuntu-latest
    needs: validate-plan
    if: ${{ github.event_name == 'workflow_dispatch' && needs.detect-changes.outputs.dirs != '[]' }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.detect-changes.outputs.dirs) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Install Terragrunt
        run: |
          sudo curl -L -o /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.0/terragrunt_linux_amd64
          sudo chmod +x /usr/local/bin/terragrunt

      - name: Terragrunt Apply
        run: |
          terragrunt run-all apply --terragrunt-working-dir=${{ matrix.dir }} --terragrunt-non-interactive -auto-approve
